
# === AQUAWARP ===
#
# (c) Created by Anh Craft. Apache License.
#
# *****************************************

# allow this plugin can check update
checkUpdate: true

# allow this plugin can support PlaceHolderAPI (require PlaceHolderAPI)
# if changed it, you must be reload this plugin and PlaceholderAPI!
supportPlaceHolderAPI: false

# allow this plugin can support MVdWPlaceholderAPI (require MVdWPlaceholderAPI)
# if changed it, you must be reload this plugin and MVdWPlaceholderAPI!
# you can use placeholders for FeatherBoard :)
supportMVdWPlaceholderAPI: false

# language file (in messages folder)
# available: en (English), vi (Vietnamese), de (German), ru (Russian)
lang: message_en.yml

# hash function using in this plugin
# available: plain_text (*), sha256, sha512, md5, base64 (*)
hash: md5


# MySQL configuration
mysql:
  # the prefix will show in the first of table name, such as: aquawarp_warps
  prefix: aquawarp_
  
  table:
    collate: utf8_unicode_ci
    charset: utf8
    # MariaDB or InnoDB
    engine: InnoDB
    
  host: localHost       # (default)
  port: '3306'          # (default)
  user: root            # (default)
  pass: ''              # (default)
  database: minecraft   # your database name
  
  
# HelpWarp configuration
helpWarp:
  messages:
  - "&c---------------------------------&r"
  - "&a-=[ &r&5%plugin_name%&r&a &bv%plugin_version%&r&a ]=-&r"
  - "&5"
  - "&6/warp <name> [<player>]&r  &a[+] Teleport you or other player to a warp&r"
  - "&6/warps&r  &a[+] All commands of this plugin (Help)&r"
  - "&6/warps set <name> [<x> <y> <z> <yaw> <world>]&r  &a[+] Create new warp&r"
  - "&6/warps del <name>&r  &a[+] Delete a warp&r"
  - "&6/warps list&r  &a[+] List all warps&r"
  - "&6/warps lock <name> <pass>&r  &a[+] Lock a warp&r"
  - "&6/warps unlock <name>&r  &a[+] Unlock a warp&r"
  - "&6/warps feetp <name> <cost (for unlocked warp)> <cost (for locked warp)>&r  &a[+] Update the amount of money paid (if player teleport to a warp)&r"
  - "&6/warps gui&r  &a[+] Open the GUI&r"
  - "&6/warpadmin reload&r  &a[+] Reload the config file&r"
  - "&c---------------------------------&r"


# LockWarp configuration
lockWarp:
  # list of unsafe passwords
  unsafePassword:
  - '123456'
  - '123456789'
  - '123123'
  - '1234'
  - '123'
  - admin
  - password
  - abc123
  - abcxyz
  - login


# DelWarp configuration
delWarp:
  # if you delete a locked warp, that warp will be unlocked
  unlockIfDeleteWarp: true


# WarpGUI configuration
warpGUI:
  warpLore:
  - '&5To @warp'
  - '&c'
  - '&bMinecraft Server'


# TpWarp configuration
tpWarp:
  # list of commands will execute before or after warping
  exeCmdBeforeWarping:
  - tell {player_name} Teleporting you to {warp_name} warp...
  exeCmdAfterWarping:
  - give {player_name} {player_iteminhand_name} 1
  
  # enable service charges
  serviceCharge: false
  
  # default service costs
  defaultServiceCost: 0
  
  # allow play sounds or spawn effects after the player teleport to a warp
  effect: true
  sound: true
  
  # energy configuration
  energy:
    enable: false
    
    # maximum energy the player have
    maxEnergy: 100
    
    # minimum energy needed to teleport to a locked warp
    energyNeededWarpLocked: 10
    
    # minimum energy needed to teleport to an unlocked warp
    energyNeededWarpUnLocked: 5
    
    # energy consumption whenever teleport to a locked warp
    energyConsumptionWarpLocked: 10
    
    # energy consumption whenever teleport to an unlocked warp
    energyConsumptionWarpUnLocked: 5
    
    # reset the energy when the player join
    reset: true
    
    # energy recovery time
    energyRecoveryTime: 1000 # 1 minute
    
    # the maximum amount of energy will recovery (every {energy-recovery-time})
    # it will recover the amount of energy is equal to the maximum energy
    energyRecoveryAmount: 10
    
    # energy recovery for offline players
    energyRecoveryForOffline: true