
# === AQUAWARP ===
#
# (c) Created by Anh Craft. Apache License.
#
# *****************************************

# allow this plugin can check update
checkUpdate: true

# language file (in messages folder)
# available: en, vi
lang: message_en.yml

# hash function using in this plugin
# available: plain_text (*), sha256, sha512, md5, base64 (*)
hash: md5

# MySQL configuration
mysql:
  # the prefix will show in the first of table name, such as: aquawarp_warps
  prefix: aquawarp_
  
  table:
    collate: utf8_unicode_ci
    charset: utf8
    # MariaDB or InnoDB
    engine: InnoDB
    
  host: localHost       # (default)
  port: '3306'          # (default)
  user: root            # (default)
  pass: ''              # (default)
  database: minecraft   # your database name

# LockWarp configuration
lockWarp:
  # list of unsafe passwords
  unsafePassword:
  - '123456'
  - '123456789'
  - '123123'
  - '1234'
  - '123'
  - admin
  - password
  - abc123
  - abcxyz
  - login

# DelWarp configuration
delWarp:
  # if you delete a locked warp, that warp will be unlocked
  unlockIfDeleteWarp: true

# WarpGUI configuration
warpGUI:
  warpLore:
  - '&5To @warp'
  - '&c'
  - '&bMinecraft Server'

# TpWarp configuration
tpWarp:
  # list of commands will execute before warping
  exeCmdBeforeWarping:
  - tell {player_name} Teleporting you to {warp_name} warp...
  
  # list of commands will execute after warping
  exeCmdAfterWarping:
  - give {player_name} {player_iteminhand_name} 1
  
  # enable service charges
  serviceCharge: false
  effect: true
  sound: true
