name: AquaWarp
main: vn.anhcraft.aquawarp.AquaWarp
version: 1.3.6
website: http://anhcraft.tk/
description: "(c) by Anh Craft"
author: "Anh Craft"
softdepend: [PlaceholderAPI,MVdWPlaceholderAPI]
contributor: "Banbeucmas"
translator: "Anh Craft, Banbeucmas, Gomze, ExZotic"
commands:
   warp:
      description: AquaWarp
   warps:
      description: AquaWarp
   warpadmin:
      description: AquaWarp
   aquawarp:
      description: AquaWarp