name: AquaWarp
main: vn.anhcraft.aquawarp.main.AquaWarp
version: 1.2.8
website: http://anhcraft.tk/
depend: [Vault]
description: "(c) by Anh Craft"
author: "Anh Craft"
commands:
   warp:
      description: AquaWarp -=[Warp]=-
   warps:
      description: AquaWarp -=[Warps]=-