name: AquaWarp
main: vn.anhcraft.aquawarp.AquaWarp
version: 1.3.2
website: http://anhcraft.tk/
depend: [Vault]
softdepend: [Vault]
description: "(c) by Anh Craft"
author: "Anh Craft"
contributor: "Banbeucmas"
translator: "Anh Craft, Banbeucmas, Gomze"
commands:
   warp:
      description: AquaWarp
   warps:
      description: AquaWarp
   warpadmin:
      description: AquaWarp
   aquawarp:
      description: AquaWarp