name: AquaWarp
version: 1.4.4
main: org.anhcraft.aquawarp.AquaWarp
depends:
- SpaciousLib
- Vault
loadbefore:
- SpaciousLib
- Vault
authors: [AnhCraft]
description: (c) by Anh Craft
website: https://anhcraft.org/
translator: "Anh Craft"
commands:
   warp:
      description: User command
   warps:
      description: Admin commands
   warpadmin:
      description: Admin commands
   aquawarp:
      description: About AquaWarp